# Generated by Django 4.1.3 on 2022-11-21 09:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetaGroup',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('EIN', models.IntegerField()),
                ('beta_testersfor_GSOC', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('street', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=500)),
                ('email_address', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('smaller_unit', models.CharField(max_length=500)),
                ('city_unit', models.CharField(max_length=500)),
                ('unit_country', models.CharField(max_length=500)),
                ('organisation_url', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Beta Group',
            },
        ),
        migrations.CreateModel(
            name='BiPySoLegal2012',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('nation', models.CharField(max_length=300)),
                ('CAMEO', models.CharField(max_length=300)),
                ('Threedigit', models.IntegerField()),
                ('net', models.CharField(max_length=300)),
                ('BioPsySoci', models.FloatField()),
                ('Legal', models.FloatField()),
                ('Unk', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'BiPySoLegal2012',
            },
        ),
        migrations.CreateModel(
            name='Clientsnonus',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('EIN_us_affiliate', models.CharField(max_length=300)),
                ('name_of_organization', models.CharField(max_length=300)),
                ('contact_in_country', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Clients Non US',
            },
        ),
        migrations.CreateModel(
            name='CLIENTSUS',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('EIN', models.IntegerField()),
                ('organ', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('zipcode', models.IntegerField()),
                ('country', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'CLIENTSUS',
            },
        ),
        migrations.CreateModel(
            name='FISPUN',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('nation', models.CharField(max_length=100)),
                ('CAMEO', models.CharField(max_length=100)),
                ('FIPS', models.CharField(max_length=100)),
                ('UN', models.CharField(max_length=100)),
                ('Threedigit', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'FISPUN',
            },
        ),
        migrations.CreateModel(
            name='WaterConsumption',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Suburb', models.CharField(max_length=100)),
                ('NoOfSingleResProp', models.IntegerField()),
                ('AvgMonthlyKL', models.IntegerField()),
                ('AvgMonthlyKLPredicted', models.IntegerField()),
                ('PredictionAccuracy', models.IntegerField()),
                ('Month', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('DateTime', models.DateTimeField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'WaterConsumption',
            },
        ),
    ]
