# Generated by Django 4.1.3 on 2022-11-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsgisapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betagroup',
            name='EIN',
        ),
        migrations.RemoveField(
            model_name='clientsus',
            name='EIN',
        ),
        migrations.AddField(
            model_name='betagroup',
            name='EINN',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='clientsus',
            name='EINN',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='beta_testersfor_GSOC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='city_unit',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='contact_person',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='email_address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='organisation_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='phone_number',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='smaller_unit',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='street',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='betagroup',
            name='unit_country',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bipysolegal2012',
            name='BioPsySoci',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bipysolegal2012',
            name='CAMEO',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bipysolegal2012',
            name='Legal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bipysolegal2012',
            name='Threedigit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bipysolegal2012',
            name='Unk',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bipysolegal2012',
            name='nation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bipysolegal2012',
            name='net',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='EIN_us_affiliate',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='contact_in_country',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='country',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='name_of_organization',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsnonus',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='city',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='contact',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='country',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='email',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='organ',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientsus',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fispun',
            name='CAMEO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fispun',
            name='FIPS',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fispun',
            name='Threedigit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fispun',
            name='UN',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fispun',
            name='nation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
