# Generated by Django 4.1.3 on 2022-12-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpsgisapp', '0003_remove_betagroup_latitude_remove_betagroup_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterconsumption',
            options={'verbose_name_plural': ''},
        ),
    ]
